### PR TITLE
make tangld usable on the most basic level

### PR DESCRIPTION
**Pull request by Luis-Henriquez-Perez**
The purpose of this commit is to make `tangld` usable.

I defined `tangld` as "usable" when the  following are true:

- [ ]  no command should raise an error (unintentionally)
- [ ] `tangld-init` should work (I think it already does)
- [ ] any commands not yet fully implemented should either do nothing except message or do as much as they can when it makes sense
- [ ] `tangled-build` should work with at least the most basic of `tangld-install-type`
- [ ] we should have tests for the above

Feel free to mention if you want to add anything to these prereqs.

### CODE REVIEW

**Comment by aldrichtr** [comment]
These changes definitely set the project up for future progress.   I agree that by defining the functions with the minimum functionality to not cause an error is the best approach.  Also, I like the addition of the tangld-message function so that the user can control the messages with the verbose setting.

I'd like to separate the functions out into separate files, with a structure like so:
- tangld.el :: Initial entry point.  Set's up the customization group, requires the other files into the current environment.  Everything in the current file down to the ";;;; Initialization - tangld-init" line
- tangld-build.el ::  tangld-build function and supporting variables and functions
- tangld-init.el :: tangld-init function and supporting variables 

I think the other functions will eventually rate their own file, but they are small enough now to leave in tangld.el for the moment.  It seems like that is the general layout of most emacs packages I see.

**Comment by Luis-Henriquez-Perez** [comment]
@aldrichtr Ok. I'll separate them out as soon as I get them working.

**Comment by aldrichtr** [comment]
> @aldrichtr Ok. I'll separate them out as soon as I get them working.
> 
> EDIT: which should be today.
Awesome, thanks.  I also wanted to get your opinion on merges.  I really like how you organize each atomic change into separate commits, which makes it really easy to see what changes are in the PR.  However, I'm thinking that it's probably best to squash them on merge.  Is this how you see it too?

**Comment by Luis-Henriquez-Perez** [comment]
@aldrichtr the things on the list still haven't been finished. I tested `tangld-build` and it does tangle but I need to make it tangle to the right directory. I'm trying to incorporate your `ob-extended-tangle.el` which is what you created for this reason.

From now on, I'll keep my PRs small and more focused.

**Pull request merged**
